### ISSUE TITLE
Nouvelle : Annoncer entente avec la Fondation Bruny Surin

### ISSUE THREAD

**Issue by loup-brun** [corsaire-chaparral/corsaire-chaparral.org#60]
## TODO

- [x] La fondation cède gratuitement **site web**, **réseaux sociaux**, **graphisme**, **photo**
- [x] La fondation cède les **équipements résiduels** ~~en contrepartie du paiement en souffrance au club en 2018~~
- [x] Le club ne prend pas la responsabilité pour les événements passés
- [x] Entente avec la ville pour les 5 prochaines années
- [x] Image promotionnelle (logos 2 organisations)

## Infos

D'après le message de Denis Riopel :

> la fondation nous cède les droits pour le site web, réseaux sociaux, l’événement et tout les droits sur le visuel (typographie et photos) à titre gratuit. 
>
>J’ajouterais qu’il nous cède les équipements résiduels des anciennes courses (entre autres les chandails, chloroplastes, médailles...) en contrepartie du paiement final en souffrance au club pour l’édition 2018. 
>
>Que le club ne prend pas la responsabilité des événements passés et des engagements passés. Elle prendra les risques uniquement pour l’édition 2019. 
>
>Finalement que chacune des parties en fasse l’annonce publiquement. 
>
>Indiquer que les parties gardent la possibilité d’une entente ultérieure de partage des revenus s’il advenait qu’un commanditaire majeur était amené par la FBS pour l’événement.

**Comment by loup-brun** [comment]
Parler de ça dans le communiqué :

>Pour reconduire l'événement et aller plus loin, l'organisation est prise en charge par le club d'athlétisme Corsaire-Chaparral (club d'expérience)

**Comment by loup-brun** [comment]
Certification argent FQA
